// starter-Counter.tsx
//
// The component under test in exercise 2. It deliberately has more behavior
// than the minimal "increment / decrement" example in the lecture so the test
// suite has something to chew on.
//
// Features:
//   - Initial count is `initial` prop (default 0).
//   - Increment / Decrement buttons change the count by the current step.
//   - Reset button returns the count to `initial`.
//   - Advanced mode toggle shows / hides a "step size" input.
//   - The count is announced via a live region (role="status", aria-live="polite").
//
// Do not edit this file for the exercise.

import { useState } from 'react'

type CounterProps = {
  initial?: number
}

export function Counter({ initial = 0 }: CounterProps) {
  const [count, setCount] = useState(initial)
  const [step, setStep] = useState(1)
  const [advanced, setAdvanced] = useState(false)

  return (
    <section aria-labelledby="counter-heading">
      <h2 id="counter-heading">Counter</h2>

      <p role="status" aria-live="polite">
        Count: {count}
      </p>

      <div>
        <button type="button" onClick={() => setCount(c => c + step)}>
          Increment
        </button>
        <button type="button" onClick={() => setCount(c => c - step)}>
          Decrement
        </button>
        <button type="button" onClick={() => setCount(initial)}>
          Reset
        </button>
      </div>

      <div>
        <button
          type="button"
          aria-expanded={advanced}
          onClick={() => setAdvanced(a => !a)}
        >
          {advanced ? 'Hide advanced mode' : 'Show advanced mode'}
        </button>
      </div>

      {advanced && (
        <div>
          <label htmlFor="step-size-input">
            Step size
            <input
              id="step-size-input"
              type="number"
              min={1}
              value={step}
              onChange={e => setStep(Number(e.target.value) || 1)}
            />
          </label>
        </div>
      )}
    </section>
  )
}
