// starter-helpers.ts
//
// Three pure helper functions for exercise 1. Each has a clear contract; your
// job in the exercise is to write Vitest tests that pin the contracts.
//
// Do not edit this file; write tests against the existing behavior. If you
// disagree with a contract, write it down in your test file's notes — that is
// also a useful skill.

/**
 * Returns `true` when the token has expired relative to `now`.
 *
 * The token's `exp` claim is in seconds since the Unix epoch (per RFC 7519);
 * `now` is in milliseconds since the Unix epoch (matching `Date.now()`).
 *
 * Uses strict `<` so that a token whose `exp` exactly matches `now` is NOT
 * considered expired. This matches the rule "tokens are valid up to and
 * including the second of their stated expiry."
 *
 * @param token  An object with an `exp` claim. Other fields are ignored.
 * @param now    Current time in milliseconds since the epoch. Defaults to Date.now().
 */
export function isExpired(token: { exp: number }, now: number = Date.now()): boolean {
  return token.exp * 1000 < now
}

/**
 * Returns a human-readable relative time string.
 *
 * Behavior:
 *   - Absolute difference under 30 seconds   → "just now"
 *   - Absolute difference under 60 seconds   → "N seconds ago" or "in N seconds"
 *   - Absolute difference under 3,600 seconds → "N minutes ago" or "in N minutes"
 *   - Otherwise                              → "N hours ago" or "in N hours"
 *
 * Past times produce "X ago"; future times produce "in X". The boundary cases
 * use strict comparisons so that exactly 30 seconds is "30 seconds ago" (not
 * "just now") and exactly 60 seconds is "1 minutes ago" (not "60 seconds ago").
 *
 * The implementation does NOT use Intl.RelativeTimeFormat on purpose — keeping
 * it pure and stable makes it easier to test.
 *
 * @param date  The time to describe.
 * @param now   The reference "current time". Defaults to `new Date()`.
 */
export function formatRelativeTime(date: Date, now: Date = new Date()): string {
  const diffSeconds = Math.round((date.getTime() - now.getTime()) / 1000)
  const absSeconds = Math.abs(diffSeconds)
  const isFuture = diffSeconds > 0

  if (absSeconds < 30) {
    return 'just now'
  }
  if (absSeconds < 60) {
    return isFuture
      ? `in ${absSeconds} seconds`
      : `${absSeconds} seconds ago`
  }
  if (absSeconds < 3600) {
    const minutes = Math.floor(absSeconds / 60)
    return isFuture
      ? `in ${minutes} minutes`
      : `${minutes} minutes ago`
  }
  const hours = Math.floor(absSeconds / 3600)
  return isFuture
    ? `in ${hours} hours`
    : `${hours} hours ago`
}

/**
 * Returns a new object containing only the keys from `allowed` that exist on
 * `payload`. Keys in `allowed` that are not in `payload` are skipped (no
 * `undefined` filler). Keys in `payload` that are not in `allowed` are dropped.
 *
 * Does NOT mutate the input. Returns a fresh object.
 *
 * Use case in the Week 10 codebase: stripping a JWT payload down to the claims
 * the UI is allowed to display, before storing in client-side state. This
 * makes it easier to audit what the UI knows.
 *
 * @param payload  The source object.
 * @param allowed  The list of keys to keep.
 */
export function pickClaims<T extends Record<string, unknown>>(
  payload: T,
  allowed: readonly (keyof T)[],
): Partial<T> {
  const out: Partial<T> = {}
  for (const key of allowed) {
    if (Object.prototype.hasOwnProperty.call(payload, key)) {
      out[key] = payload[key]
    }
  }
  return out
}

/**
 * Bonus helper for exercise homework: returns the number of distinct unique
 * tokens in an array of strings. Used by one of the homework questions.
 *
 * @param tokens  An array of strings, some of which may be duplicates.
 */
export function distinctCount(tokens: readonly string[]): number {
  return new Set(tokens).size
}
